// data.js — Static city data for Hotel Antique Split PWA
// Split, Croatia — points of interest and curated walking routes

const HOTEL_COORDS = { lat: 43.5088, lng: 16.4401 };

// ── Points of Interest ───────────────────────────────────────────────────────
// Each POI: id, name, category, shortDesc, longDesc, visit (duration),
//           dist (walking distance from hotel), coords, nav (Google Maps URL)

const POIS = [
  {
    id: 'diocletian-palace',
    name: "Diocletian's Palace",
    category: 'Historic Site',
    shortDesc: "A remarkably preserved Roman emperor's retirement palace, still inhabited after 1,700 years.",
    longDesc: "Built by Emperor Diocletian between AD 295 and 305 as his retirement residence, this UNESCO-listed palace is one of the best-preserved Roman complexes in the world. Today it forms the living heart of Split's old town, with restaurants, bars, boutiques and homes woven into its ancient walls. Wander the labyrinthine lanes, discover hidden courtyards, and look up to find Roman arches framing the sky above modern apartments.",
    visit: '1–2 hrs',
    dist: '2 min walk',
    coords: { lat: 43.5082, lng: 16.4402 },
    nav: 'https://www.google.com/maps/dir/?api=1&destination=43.5082,16.4402',
  },
  {
    id: 'cathedral-of-saint-domnius',
    name: 'Cathedral of Saint Domnius',
    category: 'Religious Site',
    shortDesc: "One of the world's oldest cathedrals, built inside Diocletian's own mausoleum.",
    longDesc: "Consecrated in the 4th century, this extraordinary cathedral was converted from Emperor Diocletian's mausoleum — making it one of the oldest in continuous use anywhere on earth. The octagonal structure is crowned by a Romanesque-Gothic bell tower added in the 13th century. Climb the tower for panoramic views over the old town rooftops and the Adriatic beyond. Inside, marvel at intricately carved choir stalls and a 13th-century pulpit.",
    visit: '45 min',
    dist: '3 min walk',
    coords: { lat: 43.5080, lng: 16.4404 },
    nav: 'https://www.google.com/maps/dir/?api=1&destination=43.5080,16.4404',
  },
  {
    id: 'golden-gate',
    name: 'Golden Gate',
    category: 'Historic Site',
    shortDesc: "The grandest of the palace's four original gates, facing north toward the old land road.",
    longDesc: "Porta Aurea — the Golden Gate — was the most ceremonial entrance to Diocletian's Palace, reserved for official processions arriving from Salona. Standing just outside its massive arch is the towering bronze statue of Bishop Gregory of Nin by Ivan Meštrović. Locals say rubbing the bishop's toe brings good luck, and the gleaming bronze gives this away immediately. The gate's inner and outer facades are remarkably intact, offering a vivid sense of Roman military architecture.",
    visit: '20 min',
    dist: '7 min walk',
    coords: { lat: 43.5098, lng: 16.4398 },
    nav: 'https://www.google.com/maps/dir/?api=1&destination=43.5098,16.4398',
  },
  {
    id: 'silver-gate',
    name: 'Silver Gate',
    category: 'Historic Site',
    shortDesc: "The eastern gate of the palace, opening onto the lively Pazar street market.",
    longDesc: "The Silver Gate (Porta Argentea) marks the eastern boundary of Diocletian's Palace and opens directly onto the open-air Pazar market — a wonderful contrast of ancient stone and everyday Dalmatian life. The gate itself is beautifully preserved, with twin towers flanking its arched passage. Pass through to find vendors selling local produce, lavender sachets, and handmade goods just steps from 1,700-year-old walls.",
    visit: '15 min',
    dist: '4 min walk',
    coords: { lat: 43.5083, lng: 16.4420 },
    nav: 'https://www.google.com/maps/dir/?api=1&destination=43.5083,16.4420',
  },
  {
    id: 'iron-gate',
    name: 'Iron Gate',
    category: 'Historic Site',
    shortDesc: "The western gate of the palace, the smallest and most intimate of the four.",
    longDesc: "Porta Ferrea — the Iron Gate — is the westernmost entrance to the palace complex and the least imposing of the four gates, reflecting its secondary role as a service entrance facing the town of Salona. Above the outer arch sits a small church, Our Lady of the Bell Tower, whose medieval campanile rises dramatically above the gate. The surrounding area spills into the People's Square (Narodni Trg), historically the centre of medieval Split.",
    visit: '15 min',
    dist: '5 min walk',
    coords: { lat: 43.5079, lng: 16.4385 },
    nav: 'https://www.google.com/maps/dir/?api=1&destination=43.5079,16.4385',
  },
  {
    id: 'peristyle',
    name: 'Peristyle',
    category: 'Historic Site',
    shortDesc: "The ceremonial central square of the palace — a magnificent open-air Roman hall.",
    longDesc: "The Peristyle was the grand ceremonial forecourt of Diocletian's mausoleum and temples. Flanked by colonnaded porticos and approached by a monumental staircase, it was where the emperor received homage. Today it remains the social heart of the old town — Spalatini gather here for coffee, tourists pause in wonder, and the space transforms at night into an atmospheric outdoor venue. The black granite Egyptian sphinx on the steps dates from around 1400 BC.",
    visit: '30 min',
    dist: '2 min walk',
    coords: { lat: 43.5081, lng: 16.4403 },
    nav: 'https://www.google.com/maps/dir/?api=1&destination=43.5081,16.4403',
  },
  {
    id: 'vestibule',
    name: 'Vestibule',
    category: 'Historic Site',
    shortDesc: "A dramatic domed Roman anteroom — open to the sky after its ceiling collapsed centuries ago.",
    longDesc: "The Vestibule was once the ceremonial entrance hall leading from the Peristyle to Diocletian's private apartments. Its circular domed roof collapsed long ago, leaving a hauntingly beautiful open-air rotunda. Stand inside and look up through the circular oculus to the sky — the walls, still covered with traces of marble cladding, rise around you in perfect Roman proportions. A small door in the back leads to the atmospheric substructures beneath the palace.",
    visit: '20 min',
    dist: '2 min walk',
    coords: { lat: 43.5079, lng: 16.4405 },
    nav: 'https://www.google.com/maps/dir/?api=1&destination=43.5079,16.4405',
  },
  {
    id: 'split-city-museum',
    name: 'Split City Museum',
    category: 'Museum',
    shortDesc: "Housed in a medieval Gothic palace, tracing the full sweep of Split's layered history.",
    longDesc: "Set inside the 15th-century Papalić Palace — one of the finest examples of Gothic architecture in Dalmatia — the City Museum takes visitors from prehistoric Illyrian settlements through Roman rule, medieval Croatian kingdoms, Venetian occupation and up to the 20th century. The building itself is as compelling as the collection: soaring vaulted ceilings, stone-carved windows, and a courtyard that feels unchanged from the 1400s. Allow an hour to do it justice.",
    visit: '1 hr',
    dist: '4 min walk',
    coords: { lat: 43.5085, lng: 16.4396 },
    nav: 'https://www.google.com/maps/dir/?api=1&destination=43.5085,16.4396',
  },
  {
    id: 'mestrovic-gallery',
    name: 'Meštrović Gallery',
    category: 'Museum',
    shortDesc: "Croatia's greatest sculptor created this villa-museum to display his own monumental works.",
    longDesc: "Ivan Meštrović (1883–1962), one of the foremost sculptors of the 20th century, built this imposing white villa on the western slopes of Marjan Hill as both home and permanent gallery. The building itself — designed by Meštrović — is architecturally striking: a colonnaded terrace overlooks the sea, and some of the largest sculptures occupy the garden. Inside, bronze, marble and wood works span six decades of his career. The adjacent Kaštelet chapel contains his extraordinary wooden Life of Christ cycle.",
    visit: '1.5 hrs',
    dist: '25 min walk',
    coords: { lat: 43.5072, lng: 16.4213 },
    nav: 'https://www.google.com/maps/dir/?api=1&destination=43.5072,16.4213',
  },
  {
    id: 'marjan-hill',
    name: 'Marjan Hill Park',
    category: 'Nature',
    shortDesc: "Split's beloved forested peninsula — pine-scented trails, sea views and quiet coves.",
    longDesc: "Marjan is the green lung and spiritual retreat of Split: a forested limestone ridge that juts west from the old town into the Adriatic. Criss-crossed with walking and cycling paths, it offers spectacular views north to the Dinaric Alps and south across the islands. Small stone chapels cling to its rocky flanks, some dating from medieval hermits. At the tip you can descend to secluded swimming coves rarely discovered by visitors. The ascent via the steep staircase from Varoš quarter takes about 20 minutes.",
    visit: '2–3 hrs',
    dist: '20 min walk',
    coords: { lat: 43.5081, lng: 16.4181 },
    nav: 'https://www.google.com/maps/dir/?api=1&destination=43.5081,16.4181',
  },
  {
    id: 'bacvice-beach',
    name: 'Bačvice Beach',
    category: 'Beach',
    shortDesc: "Split's famous sandy beach — birthplace of picigin, the city's beloved barefoot ball game.",
    longDesc: "Bačvice is the most beloved and accessible beach in Split, a short stroll south of the old town. Its shallow, crystal-clear waters are ideal for swimming and — uniquely — for playing picigin, the traditional Dalmatian sport of keeping a small ball airborne above knee-deep water. The beach is lined with bars and restaurants and buzzes with locals from morning to night. In summer it stays lively well past midnight; come morning for calmer waters and a sunbed without queuing.",
    visit: '2 hrs',
    dist: '12 min walk',
    coords: { lat: 43.5031, lng: 16.4447 },
    nav: 'https://www.google.com/maps/dir/?api=1&destination=43.5031,16.4447',
  },
  {
    id: 'klis-fortress',
    name: 'Klis Fortress',
    category: 'Historic Site',
    shortDesc: "A dramatic clifftop fortress above Split with sweeping views over the coast and islands.",
    longDesc: "Perched 360 metres above sea level on the rocky cliffs above Split, Klis Fortress has guarded the narrow pass through the Dinaric Alps since at least Roman times. Most recently famous as a filming location for Game of Thrones (the Slaver's Bay city of Meereen), the fortress has a layered history of Illyrian, Roman, Croatian, Hungarian and Ottoman occupation. The views from the walls are extraordinary — on a clear day you can see the islands of Brač and Šolta. Accessible by car or bus (line 22) in about 20 minutes.",
    visit: '1.5 hrs',
    dist: '20 min by car',
    coords: { lat: 43.5581, lng: 16.5303 },
    nav: 'https://www.google.com/maps/dir/?api=1&destination=43.5581,16.5303',
  },
  {
    id: 'trogir',
    name: 'Trogir Old Town',
    category: 'Day Trip',
    shortDesc: "A perfectly preserved medieval island city, UNESCO-listed and reachable in 30 minutes.",
    longDesc: "Just 27 km west of Split, Trogir is a tiny island city whose medieval urban fabric is so intact it has been listed as a UNESCO World Heritage Site. Connected to the mainland and the island of Čiovo by two drawbridges, its compact old town is a labyrinth of Romanesque, Gothic and Renaissance buildings. The Cathedral of Saint Lawrence has a famous 13th-century portal by Master Radovan — arguably the finest example of Romanesque sculpture in Croatia. Regular buses and ferries connect Trogir with Split.",
    visit: 'Half day',
    dist: '30 min by bus',
    coords: { lat: 43.5169, lng: 16.2511 },
    nav: 'https://www.google.com/maps/dir/?api=1&destination=43.5169,16.2511',
  },
  {
    id: 'riva-promenade',
    name: 'Riva Promenade',
    category: 'Landmark',
    shortDesc: "Split's sunny seafront promenade — palms, café terraces and views across to the islands.",
    longDesc: "The Riva is the beating heart of modern Split: a long marble-paved promenade running along the southern face of Diocletian's Palace with the open sea on one side and the ancient palace walls on the other. Lined with palm trees, café terraces and the ever-present sound of seagulls, it's where Spalatini come to promenade, gossip, sip coffee, and watch ferries depart for the islands. The view from the Riva — especially at sunset — is one of the most iconic in Croatia.",
    visit: '30 min',
    dist: '1 min walk',
    coords: { lat: 43.5076, lng: 16.4403 },
    nav: 'https://www.google.com/maps/dir/?api=1&destination=43.5076,16.4403',
  },
  {
    id: 'pazar-market',
    name: 'Pazar Market',
    category: 'Market',
    shortDesc: "An open-air produce market outside the Silver Gate — cheese, olives, lavender and figs.",
    longDesc: "The Pazar is Split's daily open-air market, held just outside the eastern Silver Gate of Diocletian's Palace. It's a sensory feast: stalls heaped with seasonal vegetables, local cheeses, prošek wine, dried figs, jars of olive oil, dried lavender and the distinctive Dalmatian herb blend called mirodije. Arrive before 10 am for the best selection and freshest produce. The market is at its liveliest on Saturday mornings when farmers come in from surrounding villages.",
    visit: '30 min',
    dist: '4 min walk',
    coords: { lat: 43.5088, lng: 16.4426 },
    nav: 'https://www.google.com/maps/dir/?api=1&destination=43.5088,16.4426',
  },
  {
    id: 'archaeological-museum',
    name: 'Archaeological Museum',
    category: 'Museum',
    shortDesc: "Croatia's oldest museum, with a superb collection of Roman, early Christian and medieval finds.",
    longDesc: "Founded in 1820, the Archaeological Museum of Split is the oldest museum in Croatia. Its collections cover over three millennia of history in the region — from prehistoric finds to Illyrian artefacts, Greek colonial objects, a significant Roman collection (including excellent mosaic floors and sculpture), early Christian sarcophagi and medieval Croatian artefacts. The open-air lapidarium in the courtyard is particularly rewarding, with inscribed tombstones and architectural fragments laid out among orange trees.",
    visit: '1.5 hrs',
    dist: '15 min walk',
    coords: { lat: 43.5138, lng: 16.4386 },
    nav: 'https://www.google.com/maps/dir/?api=1&destination=43.5138,16.4386',
  },
  {
    id: 'hnk-theatre',
    name: 'HNK National Theatre',
    category: 'Cultural',
    shortDesc: "Split's grand Croatian National Theatre — opera, drama and ballet in a 19th-century building.",
    longDesc: "The Croatian National Theatre in Split (HNK) was built in 1893 in a late Renaissance style and remains one of the most important cultural institutions in Dalmatia. The theatre stages opera, ballet and drama performances throughout the year. Even if you don't attend a performance, the ornate facade and People's Square setting (Trg Gaje Bulata) are worth a look. Check the programme online — ticket prices are very reasonable by Western European standards.",
    visit: '30 min (exterior)',
    dist: '8 min walk',
    coords: { lat: 43.5092, lng: 16.4376 },
    nav: 'https://www.google.com/maps/dir/?api=1&destination=43.5092,16.4376',
  },
  {
    id: 'mestrovic-kastel',
    name: 'Meštrović Kaštelet',
    category: 'Museum',
    shortDesc: "A 16th-century fortified mansion converted by Meštrović into a chapel for his wooden Life of Christ.",
    longDesc: "A short walk from the Meštrović Gallery stands the Kaštelet — a 16th-century Renaissance palace that the sculptor purchased and converted into a private chapel to house his most ambitious project: a cycle of 28 wooden reliefs depicting the Life of Christ. Carved between 1916 and 1954, the reliefs fill the small Church of the Holy Cross with an otherworldly atmosphere. The scale, technical mastery and emotional intensity of the wood carving are remarkable. Combination tickets with the main gallery are available.",
    visit: '45 min',
    dist: '28 min walk',
    coords: { lat: 43.5069, lng: 16.4196 },
    nav: 'https://www.google.com/maps/dir/?api=1&destination=43.5069,16.4196',
  },
  {
    id: 'matejuska-port',
    name: 'Matejuška Port',
    category: 'Landmark',
    shortDesc: "A tiny historic fishing harbour at the western edge of the old town, lined with colourful boats.",
    longDesc: "Matejuška is Split's oldest and most charming fishing harbour, tucked between the old town and the beginning of the Marjan peninsula. A row of small fishing boats bobs in the harbour while local fishermen tend nets or sell their catch straight from the dock. The tiny port has been in use since at least the 16th century. The surrounding area has some of Split's best small seafood restaurants and konobas (traditional taverns) where you can eat very well without paying tourist prices.",
    visit: '20 min',
    dist: '10 min walk',
    coords: { lat: 43.5079, lng: 16.4346 },
    nav: 'https://www.google.com/maps/dir/?api=1&destination=43.5079,16.4346',
  },
  {
    id: 'veli-varos',
    name: 'Veli Varoš Quarter',
    category: 'Neighbourhood',
    shortDesc: "The oldest Croatian neighbourhood in Split — narrow lanes, stone houses and the real local life.",
    longDesc: "Nestled between the palace walls and the slopes of Marjan Hill, Veli Varoš is the oldest Croatian settlement in Split, predating Venetian rule. Its dense tangle of narrow stone alleyways, flower-filled courtyards and centuries-old churches feels entirely different from the Roman palace district nearby. This is where old Split lives and breathes — neighbours call across balconies, cats sleep on warm stone doorsteps, and small konobas serve honest Dalmatian food to locals who've been eating there for decades.",
    visit: '45 min',
    dist: '12 min walk',
    coords: { lat: 43.5082, lng: 16.4355 },
    nav: 'https://www.google.com/maps/dir/?api=1&destination=43.5082,16.4355',
  },
  {
    id: 'sustipan-park',
    name: 'Sustipan Park',
    category: 'Nature',
    shortDesc: "A serene clifftop park at the western tip of the old town, with benches overlooking the sea.",
    longDesc: "Sustipan is a small terraced park built on a rocky promontory at the western edge of Split's seafront, overlooking the ferry port and the open Adriatic. Once the site of a 6th-century Benedictine monastery (traces remain in the old cemetery), it is now a quiet park with stone benches, pine trees and sweeping views across the water toward the island of Šolta. It's one of the best spots in Split to watch the sunset — arrive 30 minutes before dusk for the best light.",
    visit: '30 min',
    dist: '18 min walk',
    coords: { lat: 43.5064, lng: 16.4315 },
    nav: 'https://www.google.com/maps/dir/?api=1&destination=43.5064,16.4315',
  },
];

// ── Routes ──────────────────────────────────────────────────────────────────
// Each route: id, name, type, duration, shortDesc, longDesc,
//             startPoint {name, coords}, poiIds, profile

const ROUTES = [
  {
    id: 'old-town-essentials',
    name: 'Old Town Essentials',
    type: 'Walking',
    duration: '~90 min',
    shortDesc: "The best introduction to Split — palace gates, the Peristyle, cathedral and the Riva.",
    longDesc: "This route takes you through the unmissable highlights of Diocletian's Palace and the old town. Begin at the Bronze Gate on the Riva and move north through the underground substructures, emerging onto the Peristyle. Visit the Cathedral of Saint Domnius, pause at the Vestibule, then walk east to the Silver Gate and north to the Golden Gate. Return through the lanes past the City Museum and finish with a coffee on the Riva watching the ferries.",
    startPoint: { name: 'Riva Promenade (Bronze Gate)', coords: { lat: 43.5076, lng: 16.4403 } },
    poiIds: [
      'riva-promenade',
      'peristyle',
      'vestibule',
      'cathedral-of-saint-domnius',
      'silver-gate',
      'golden-gate',
      'iron-gate',
    ],
    profile: 'Perfect for first-time visitors, families and anyone who wants to understand Split in a single focused walk.',
  },
  {
    id: 'marjan-hill-escape',
    name: 'Marjan Hill Escape',
    type: 'Nature',
    duration: '~3 hrs',
    shortDesc: "Climb above the city into pine forest, with sea views, chapels and quiet swimming coves.",
    longDesc: "Escape the city crowds entirely on this half-day route through Marjan Hill Park. Begin in Veli Varoš and climb the steep stone staircase to the park, following paths west past medieval stone chapels and panoramic viewpoints. Descend to the Meštrović Gallery for a world-class collection, then continue to the Kaštelet chapel. End with a late lunch at Matejuška fishing harbour.",
    startPoint: { name: 'Veli Varoš, Šperun ulica', coords: { lat: 43.5082, lng: 16.4355 } },
    poiIds: [
      'veli-varos',
      'marjan-hill',
      'mestrovic-gallery',
      'mestrovic-kastel',
      'matejuska-port',
    ],
    profile: 'Ideal for active guests, nature lovers and those looking to escape the crowds. Wear comfortable shoes — the paths are uneven.',
  },
  {
    id: 'coastal-walk-beaches',
    name: 'Coastal Walk & Beaches',
    type: 'Leisure',
    duration: '~2 hrs',
    shortDesc: "Follow the seafront south from the Riva to the famous Bačvice beach and beyond.",
    longDesc: "Start on the Riva and stroll south along the seafront promenade past the city park and beach terraces. Reach Bačvice — Split's beloved sandy beach — for a swim or to watch locals play picigin. Continue east along the Žnjan coastal path if you have energy for more secluded coves. Return via the same path or catch a tram back to the centre.",
    startPoint: { name: 'Riva Promenade', coords: { lat: 43.5076, lng: 16.4403 } },
    poiIds: [
      'riva-promenade',
      'bacvice-beach',
    ],
    profile: 'Great for warm afternoons, beach lovers and families. Bring swimwear, sunscreen and water.',
  },
  {
    id: 'unesco-deep-dive',
    name: 'UNESCO Deep Dive',
    type: 'Cultural',
    duration: '~2.5 hrs',
    shortDesc: "An in-depth exploration of the Roman and medieval layers inside the palace walls.",
    longDesc: "For those who want to go deeper than a standard sightseeing tour, this route focuses on the archaeological and architectural riches inside Diocletian's Palace. Begin at the underground Substructures (enter from the Riva Bronze Gate) to understand the palace layout from below. Move up through the Peristyle, climb the Cathedral bell tower for aerial views, visit the City Museum in the Gothic Papalić Palace, then trace each of the four gates. End at the Pazar market for local produce.",
    startPoint: { name: 'Bronze Gate / Palace Substructures', coords: { lat: 43.5076, lng: 16.4403 } },
    poiIds: [
      'diocletian-palace',
      'peristyle',
      'vestibule',
      'cathedral-of-saint-domnius',
      'split-city-museum',
      'golden-gate',
      'silver-gate',
      'iron-gate',
      'pazar-market',
    ],
    profile: 'Recommended for history enthusiasts, architecture lovers and guests on longer stays who want a thorough understanding of Split.',
  },
  {
    id: 'local-neighbourhood-walk',
    name: 'Local Neighbourhood Walk',
    type: 'Cultural',
    duration: '~1.5 hrs',
    shortDesc: "Discover the authentic Split that tourists miss — markets, old quarters and local bars.",
    longDesc: "Leave the palace district and explore the real Split that locals inhabit. Begin at the Pazar market for a taste of everyday Dalmatian commerce, then wander into the Veli Varoš quarter to explore its medieval lanes. Continue to Matejuška fishing harbour to watch the fishermen and sample the city's best konobas. The route finishes at the Archaeological Museum, Croatia's oldest, before an evening return to the Riva.",
    startPoint: { name: 'Pazar Market (Silver Gate)', coords: { lat: 43.5088, lng: 16.4426 } },
    poiIds: [
      'pazar-market',
      'veli-varos',
      'matejuska-port',
      'archaeological-museum',
    ],
    profile: 'Perfect for curious travellers who want local atmosphere over monument-ticking.',
  },
  {
    id: 'sunset-viewpoints',
    name: 'Sunset & Viewpoints',
    type: 'Scenic',
    duration: '~1.5 hrs',
    shortDesc: "The best vantage points in Split to watch the Adriatic sun sink behind the islands.",
    longDesc: "Split's topography provides spectacular sunset viewpoints. This route chains the best of them in a single late-afternoon walk. Start at Sustipan Park for open sea views, then climb to Marjan Hill's Telegrin peak — the highest point — for a 360-degree panorama. Descend through the park and finish on the Riva promenade as the last light fades and the palace walls glow gold. The whole walk works best from about 90 minutes before sunset.",
    startPoint: { name: 'Sustipan Park entrance', coords: { lat: 43.5064, lng: 16.4315 } },
    poiIds: [
      'sustipan-park',
      'marjan-hill',
      'riva-promenade',
    ],
    profile: 'Romantic and scenic. Excellent for photographers, couples and anyone wanting to end the day memorably.',
  },
];
