// whispers-data.js — Whispers of the Palace: 12 chapters (final production order)
// Static content module. Images live in pwa/story/. Replace gradient fallbacks
// with real image paths once assets are ready.
//
// Fields:
//   mainText       — editorial app text shown in chapter detail (array of paragraphs)
//   videoNarration — full cinematic narration for future video production (not shown in app)
//   videoUrl       — empty until production video is available
//   videoLabel     — shown in video placeholder inside detail screen

/* eslint-disable quotes */
const WHISPERS_CHAPTERS = [
  {
    id: 'ch01',
    number: '01',
    title: 'The Palace by the Sea',
    subtitle: 'Before Split became a city, it was an emperor’s final world by the water.',
    shortText: 'Before Split became a city, it was the final coastal residence of one of Rome’s most powerful rulers.',
    mainText: [
      'Before Split became the city you walk through today, this place was something very different: a carefully planned imperial residence by the sea.',
      'Diocletian’s Palace was built for an emperor who had ruled one of the largest empires in history — and then made the rare decision to step away from power.',
      'Here, stone, water, ceremony and protection came together. What began as a Roman palace would slowly become the living heart of Split.',
    ],
    didYouKnow: 'Diocletian is one of the rare Roman emperors who voluntarily gave up power.',
    image: 'story/palace-by-the-sea.jpg',
    gradient: 'linear-gradient(160deg, #0a1824 0%, #0e2d40 55%, #0a2030 100%)',
    videoUrl: '',
    videoLabel: 'Cinematic story planned',
    videoNarration: [
      'Before Split was a city, it was a palace.',
      'Not a palace from a fairy tale, but a world of stone, order and power — built beside the sea for a Roman emperor.',
      'Diocletian ruled an empire, then did something almost unthinkable: he stepped away from power.',
      'Here, between Salona and the Adriatic, he built his final world.',
      'The walls were not meant to become streets, cafés and homes.',
      'And yet, that is exactly what happened.',
      'The emperor’s palace did not disappear into history.',
      'It became Split.',
    ],
    relatedPlace: 'Diocletian’s Palace',
    relatedPoiKey: 'diocletian_palace',
    ctaAsk: 'Ask about the Palace by the sea',
  },
  {
    id: 'ch02',
    number: '02',
    title: 'The Empire on Fire',
    subtitle: 'Before the palace, the Roman world was tearing itself apart.',
    shortText: 'For fifty years before Diocletian, the Roman Empire burned through emperors, wars and crisis.',
    mainText: [
      'The third century was one of the darkest periods in Roman history. Between 235 and 284 AD, more than fifty emperors rose and fell — most of them assassinated within months of taking power.',
      'The empire fractured under the pressure of barbarian invasions along every frontier, devastating plagues, collapsing trade and a currency that lost almost all its value. Entire provinces broke away. The idea of a unified Rome seemed close to extinction.',
      'This was the world that shaped Diocletian. A man who grew up in a fractured empire understood better than most what it would take to hold it together. The palace at the end of his story begins with this disorder.',
    ],
    didYouKnow: 'During the Crisis of the Third Century, the Roman Empire briefly split into three separate competing states simultaneously.',
    image: 'story/empire-on-fire.jpg',
    gradient: 'linear-gradient(160deg, #1a0a00 0%, #3a1800 55%, #200800 100%)',
    videoUrl: '',
    videoLabel: 'Cinematic story planned',
    videoNarration: [
      'Before the palace, there was chaos.',
      'For fifty years, the Roman world burned through emperors like candles in a wind.',
      'Assassinations, civil wars, plague and invasion followed one another without pause.',
      'The frontiers broke open.',
      'The currency collapsed.',
      'Provinces declared their own rulers.',
      'The empire that had seemed eternal came close to ending.',
      'Into this world, a soldier from Dalmatia began his rise.',
      'He had seen what disorder looked like.',
      'He intended to replace it with order.',
    ],
    relatedPlace: null,
    relatedPoiKey: null,
    ctaAsk: 'Ask about the Roman crisis',
  },
  {
    id: 'ch03',
    number: '03',
    title: 'The Soldier Who Became Emperor',
    subtitle: 'From the Dalmatian coast to the throne of Rome.',
    shortText: 'Diocletian was born into nothing. He reached the top through discipline, intelligence and force.',
    mainText: [
      'Diocletian was not born into power. He came from humble origins near Salona, on the Dalmatian coast, in the province that would eventually carry his greatest monument.',
      'He rose through the ranks of the Roman military — the path available to ambitious men without aristocratic connections. By 284 AD, after the death of the emperor Numerian, his soldiers proclaimed him emperor. The rival claimant was dead within days.',
      'He was not a man who hesitated. Diocletian restored imperial authority through force, intelligence and a systematic approach to reform that would reshape the Roman world for a generation.',
    ],
    didYouKnow: 'Diocletian’s original name may have been Diocles. He adopted the Latinised form Diocletianus after becoming emperor.',
    image: 'story/soldier-became-emperor.jpg',
    gradient: 'linear-gradient(160deg, #0e1820 0%, #1e3040 55%, #0a1218 100%)',
    videoUrl: '',
    videoLabel: 'Cinematic story planned',
    videoNarration: [
      'He was not born to rule.',
      'He was born here, on this coast, in the shadow of Salona.',
      'A soldier’s life was the only ladder available to a man without a name.',
      'And he climbed it.',
      'By 284 AD, the army had made him emperor.',
      'His rivals understood quickly what kind of man they were dealing with.',
      'Diocletian did not rule through ceremony alone.',
      'He ruled through discipline, calculation and the absolute conviction that order was worth any price.',
      'The palace you stand in today is the final expression of that conviction.',
    ],
    relatedPlace: 'Salona',
    relatedPoiKey: 'salona',
    ctaAsk: 'Ask about Diocletian’s origins',
  },
  {
    id: 'ch04',
    number: '04',
    title: 'The Emperor Who Walked Away',
    subtitle: 'The ruler who left the Roman world behind.',
    shortText: 'Diocletian’s greatest surprise was not how he ruled, but how he chose to leave power.',
    mainText: [
      'Diocletian came to power during a difficult and unstable period of Roman history. The empire was vast, restless and difficult to control.',
      'He rose through the military world and became emperor in 284 AD. His reforms changed the structure of imperial rule, strengthening the army, reorganizing administration and introducing the Tetrarchy — a system of shared rule.',
      'But his most unusual decision came later. Unlike many emperors before him, Diocletian voluntarily left power and withdrew to the Dalmatian coast.',
    ],
    didYouKnow: 'The Tetrarchy was Diocletian’s attempt to make the Roman Empire more stable by sharing imperial authority among four rulers.',
    image: 'story/emperor-who-walked-away.jpg',
    gradient: 'linear-gradient(160deg, #1a0e2e 0%, #2a1a3e 55%, #0e0e1a 100%)',
    videoUrl: '',
    videoLabel: 'Cinematic story planned',
    videoNarration: [
      'Diocletian was not born into a quiet age.',
      'The Roman Empire he inherited was vast, restless and difficult to control.',
      'He rose through the army, reached the highest power in the Roman world, and reshaped the empire with discipline and order.',
      'But the most unusual part of his story came later.',
      'Unlike many emperors before him, Diocletian chose to leave the throne.',
      'He withdrew from imperial power and returned to the Dalmatian coast.',
      'The palace he built here was not only a home.',
      'It was the final statement of a soldier-emperor who wanted order, security and memory carved into stone.',
    ],
    relatedPlace: null,
    relatedPoiKey: null,
    ctaAsk: 'Ask about the emperor who walked away',
  },
  {
    id: 'ch05',
    number: '05',
    title: 'Salona, the Lost Roman Capital',
    subtitle: 'The Roman world before Split.',
    shortText: 'Before Split rose inside the Palace walls, Salona was the great Roman city of Dalmatia.',
    mainText: [
      'Before Split, there was Salona. It was the capital of the Roman province of Dalmatia and one of the most important cities on this part of the Adriatic.',
      'Diocletian’s origins are traditionally connected with this area, near the city whose roads, walls, amphitheatre, basilicas and burial grounds shaped the Roman world around him.',
      'Salona also helps explain why the Palace was built where it was. It stood close to the Roman capital, near the sea, and near the fresh water of the Jadro River. Through an aqueduct, that water made an imperial residence on this coast possible.',
    ],
    didYouKnow: 'Salona’s ruins include an amphitheatre, early Christian remains and traces of a city that once stood at the centre of Roman Dalmatia.',
    image: 'story/salona-lost-roman-capital.jpg',
    gradient: 'linear-gradient(160deg, #2a1400 0%, #4a2800 55%, #1e1000 100%)',
    videoUrl: '',
    videoLabel: 'Cinematic story planned',
    videoNarration: [
      'Before Split, there was Salona.',
      'It was the great Roman city of Dalmatia — a place of walls, streets, temples, baths, amphitheatre, basilicas and everyday life.',
      'Diocletian’s world began near here, in the orbit of this powerful Roman capital.',
      'Salona explains why the palace was built where it was: close to the city, close to the sea, and close to the fresh water of the Jadro.',
      'Through an aqueduct, that water made an imperial residence on this coast possible.',
      'When Salona later declined, life gradually moved toward the protection of the palace walls.',
      'In that movement, the future city of Split began to take shape.',
    ],
    relatedPlace: 'Salona',
    relatedPoiKey: 'salona',
    ctaAsk: 'Ask about Salona',
  },
  {
    id: 'ch06',
    number: '06',
    title: 'Rome Reforged',
    subtitle: 'How one emperor tried to save an empire by dividing it.',
    shortText: 'Diocletian’s greatest political invention was sharing power — four rulers, one empire.',
    mainText: [
      'Diocletian understood that no single man could govern an empire as vast as Rome had become. In 293 AD, he introduced the Tetrarchy: a system of four co-rulers, two senior Augusti and two junior Caesars, each responsible for a different region.',
      'He reorganised the provinces, reformed the tax system, restructured the army and issued the Edict on Maximum Prices — an attempt to control the inflation that had crippled trade. The scale of administrative ambition was unlike anything Rome had seen.',
      'When he retired to this palace in 305 AD, the empire he handed over was stronger, more organised and more defensible than the one he had found. The reforms did not outlast him by long, but the structure of late Roman governance bore his imprint for generations.',
    ],
    didYouKnow: 'The Tetrarchy system Diocletian created was so influential that Constantine the Great — who reunified the empire — was himself originally one of its intended successors.',
    image: 'story/rome-reforged.jpg',
    gradient: 'linear-gradient(160deg, #0a180a 0%, #183018 55%, #0a1410 100%)',
    videoUrl: '',
    videoLabel: 'Cinematic story planned',
    videoNarration: [
      'One man could not hold the Roman world.',
      'Diocletian knew this.',
      'His answer was the Tetrarchy — four co-rulers, each governing a quarter of the empire.',
      'The provinces were reorganised.',
      'The army was restructured.',
      'The tax system was reformed.',
      'An edict tried to fix prices across the entire Roman world.',
      'The scale of ambition was extraordinary.',
      'Some of it held.',
      'Some of it did not.',
      'But when he finally retired to this coast, Diocletian left behind a more ordered empire than the one he had found.',
      'The palace he built here was not only a home.',
      'It was the final work of a man who had spent twenty years reforging Rome.',
    ],
    relatedPlace: null,
    relatedPoiKey: null,
    ctaAsk: 'Ask about the Tetrarchy',
  },
  {
    id: 'ch07',
    number: '07',
    title: 'A Palace, a Fortress, a Home',
    subtitle: 'A residence built with the logic of a military mind.',
    shortText: 'Diocletian’s Palace was both luxurious and defensive — a home shaped by power, order and protection.',
    mainText: [
      'Diocletian’s Palace is not a palace in the usual sense. Its walls, gates and towers give it the character of a fortified structure, while its inner spaces reveal the ceremonial and residential world of an emperor.',
      'The southern part, closer to the sea, was connected with the imperial apartments and private life. The northern part had a more practical and military character.',
      'This combination makes the Palace unique: part Roman villa, part military camp, part imperial stage.',
    ],
    didYouKnow: 'The Palace combines features of a Roman villa, a military camp and an imperial ceremonial complex.',
    image: 'story/palace-fortress-home.jpg',
    gradient: 'linear-gradient(160deg, #1e1200 0%, #3a2a10 55%, #2c1f14 100%)',
    videoUrl: '',
    videoLabel: 'Cinematic story planned',
    videoNarration: [
      'Diocletian’s Palace is not a palace in the usual sense.',
      'It was also a fortress, a residence and a carefully ordered imperial complex.',
      'Its walls and gates speak the language of protection.',
      'Its inner spaces speak the language of ceremony.',
      'The southern part was connected with the emperor’s private world by the sea, while the northern part carried a more practical and military character.',
      'This was a home built by a ruler who understood discipline, defence and display.',
      'Every wall had a purpose.',
      'Every entrance controlled movement.',
      'The palace was designed as a world within walls.',
    ],
    relatedPlace: 'Diocletian’s Palace',
    relatedPoiKey: 'diocletian_palace',
    ctaAsk: 'Ask about the Palace layout',
  },
  {
    id: 'ch08',
    number: '08',
    title: 'The Golden Gate',
    subtitle: 'The ceremonial northern entrance to the Palace.',
    shortText: 'The Golden Gate faced the road toward Salona and marked one of the Palace’s most important thresholds.',
    mainText: [
      'The Golden Gate was the grand northern entrance to Diocletian’s Palace. It faced the road toward Salona, the Roman city that shaped the wider world around the Palace.',
      'This was not simply a doorway. It was a controlled passage between the outside world and the emperor’s private domain.',
      'Today, people pass through it casually, often without stopping. But the stones still carry the memory of arrival, ceremony and power.',
    ],
    didYouKnow: 'The Golden Gate once connected the Palace with the road toward Salona.',
    image: 'story/golden-gate.jpg',
    gradient: 'linear-gradient(160deg, #2a1800 0%, #4a3010 55%, #1e1400 100%)',
    videoUrl: '',
    videoLabel: 'Cinematic story planned',
    videoNarration: [
      'The Golden Gate was the grand northern entrance to the palace.',
      'It faced the road toward Salona, the Roman capital that shaped this entire landscape.',
      'For Diocletian’s world, this was not simply a doorway.',
      'It was a controlled passage between the outside world and the emperor’s private domain.',
      'Today, people pass through it casually, often without stopping.',
      'But the stones still carry the memory of arrival, ceremony and power.',
      'To walk through the Golden Gate is to cross one of the oldest thresholds of Split.',
    ],
    relatedPlace: 'Golden Gate',
    relatedPoiKey: 'golden_gate',
    ctaAsk: 'Ask about the Golden Gate',
  },
  {
    id: 'ch09',
    number: '09',
    title: 'The Heart of the Palace',
    subtitle: 'Peristyle, Vestibule and the ceremonial world of the emperor.',
    shortText: 'At the centre of the Palace, architecture became theatre.',
    mainText: [
      'The Peristyle was the ceremonial heart of Diocletian’s Palace. Surrounded by columns and framed by sacred and imperial spaces, it was a place where architecture communicated power.',
      'From here, one could approach the imperial apartments through the Vestibule, a striking circular space that still carries a powerful sense of transition.',
      'Today, these same stones are filled with visitors, music and everyday life. Yet the ceremonial rhythm of the place can still be felt.',
    ],
    didYouKnow: 'The Vestibule is famous today for its acoustics, often used by singers and performers.',
    image: 'story/peristyle-vestibule.jpg',
    gradient: 'linear-gradient(160deg, #1a0e20 0%, #3a1a30 55%, #2c1414 100%)',
    videoUrl: '',
    videoLabel: 'Cinematic story planned',
    videoNarration: [
      'The Peristyle was the ceremonial heart of the palace.',
      'Here, architecture became theatre.',
      'Columns, steps and open space worked together to create a place where imperial power could be seen and felt.',
      'From the Peristyle, one entered the Vestibule — a striking circular space that marked the passage toward the emperor’s private apartments.',
      'Today, this same space is filled with visitors, music and everyday life.',
      'But the rhythm of ceremony has not entirely disappeared.',
      'Stand here for a moment, and the palace still knows how to speak.',
    ],
    relatedPlace: 'Peristyle and Vestibule',
    relatedPoiKey: 'peristyle',
    ctaAsk: 'Ask about the Peristyle',
  },
  {
    id: 'ch10',
    number: '10',
    title: 'The Cellars Beneath the Palace',
    subtitle: 'The hidden structure beneath the emperor’s world.',
    shortText: 'Beneath the Palace, the Roman substructures still carry the shape of what once stood above.',
    mainText: [
      'Beneath the Palace lies one of its most powerful spaces. The cellars were not built to impress like the Peristyle, but to support the emperor’s apartments above.',
      'Their structure preserved the shape of the Roman Palace more clearly than almost anywhere else. Walking through them today means moving through the hidden skeleton of Diocletian’s world.',
      'Stone arches, shadow and silence reveal what the city above has slowly transformed.',
    ],
    didYouKnow: 'The cellars help us understand the layout of the emperor’s apartments that once stood above them.',
    image: 'story/cellars-beneath-palace.jpg',
    gradient: 'linear-gradient(160deg, #0e0e0e 0%, #1c1810 55%, #0a0a0a 100%)',
    videoUrl: '',
    videoLabel: 'Cinematic story planned',
    videoNarration: [
      'Beneath the palace lies one of its most powerful spaces.',
      'The cellars were not built to impress in the way the Peristyle was built to impress.',
      'They were built to carry.',
      'Their structure supported the emperor’s apartments above and preserved the shape of the Roman palace more clearly than almost anywhere else.',
      'Walking here today, you are moving through the hidden skeleton of Diocletian’s world.',
      'Stone arches, shadow and silence reveal what the city above has slowly transformed.',
      'The cellars are not simply beneath Split.',
      'They are one of the reasons we can still understand the palace at all.',
    ],
    relatedPlace: 'Diocletian’s Cellars',
    relatedPoiKey: 'cellars',
    ctaAsk: 'Ask about the Cellars',
  },
  {
    id: 'ch11',
    number: '11',
    title: 'From Mausoleum to Cathedral',
    subtitle: 'The emperor’s tomb that became the Cathedral of Saint Domnius.',
    shortText: 'One of the Palace’s greatest historical reversals stands at its centre.',
    mainText: [
      'Diocletian built a mausoleum for himself within the Palace complex. It was intended as the final resting place of an emperor, surrounded by the symbols of Roman power.',
      'Over time, history transformed the meaning of this space. The mausoleum became the Cathedral of Saint Domnius, one of the most recognizable landmarks of Split.',
      'The transformation is deeply symbolic: an imperial tomb became a Christian cathedral dedicated to a local saint and martyr.',
    ],
    didYouKnow: 'The Cathedral of Saint Domnius is considered one of the oldest cathedral buildings still in use in its original structure.',
    image: 'story/mausoleum-cathedral.jpg',
    gradient: 'linear-gradient(160deg, #1a1000 0%, #3a2800 55%, #1e1800 100%)',
    videoUrl: '',
    videoLabel: 'Cinematic story planned',
    videoNarration: [
      'At the centre of the palace, Diocletian built his mausoleum.',
      'It was meant to be the final resting place of an emperor, surrounded by the symbols of Roman power.',
      'But history changed the meaning of this space.',
      'Over time, the mausoleum became the Cathedral of Saint Domnius, one of the most recognizable landmarks of Split.',
      'The transformation is extraordinary.',
      'An imperial tomb became a Christian cathedral dedicated to a local saint and martyr.',
      'This is the story of the palace itself: not frozen in one age, but reshaped by every century that followed.',
    ],
    relatedPlace: 'Cathedral of Saint Domnius',
    relatedPoiKey: 'cathedral_saint_domnius',
    ctaAsk: 'Ask about the Cathedral',
  },
  {
    id: 'ch12',
    number: '12',
    title: 'The Palace That Became Split',
    subtitle: 'How imperial stone became a living city.',
    shortText: 'The Palace survived because people moved into it, changed it and made it their own.',
    mainText: [
      'Many ancient monuments survive as ruins. Diocletian’s Palace survived differently. It became a city.',
      'Over the centuries, people built homes, churches, shops and streets within the Roman walls. Imperial halls became everyday passages, and ancient columns stood beside medieval houses.',
      'This is why Split feels unlike almost anywhere else. The past is not locked behind a museum door. It is under your feet, above your head and around the corner.',
      'Imagine the emperor returning now — a figure in shadow, moving through the Peristyle at dusk. Coffee cups on the steps where soldiers once stood. Children running through the gate he built for ceremony. Music rising from the square where silence was once required.',
      'He might not recognise the city. But he would recognise the stone.',
    ],
    didYouKnow: 'Today, people still live and work inside the walls of Diocletian’s Palace.',
    image: 'story/palace-became-split.jpg',
    gradient: 'linear-gradient(160deg, #0a1a1a 0%, #1a3030 55%, #102020 100%)',
    videoUrl: '',
    videoLabel: 'Cinematic story planned',
    videoNarration: [
      'Many ancient monuments survive as ruins.',
      'Diocletian’s Palace survived differently.',
      'It became a city.',
      'Over the centuries, people built homes, churches, shops and streets within the Roman walls.',
      'Imperial halls became everyday passages.',
      'Ancient columns stood beside medieval houses.',
      'The palace did not disappear.',
      'It adapted.',
      'That is why Split feels unlike almost anywhere else.',
      'The past is not locked behind a museum door.',
      'It is under your feet, above your head and around the corner.',
      'Imagine the emperor returning now — a silhouette moving through the Peristyle at dusk.',
      'Coffee cups on the steps where soldiers once stood.',
      'Children running through the gate he built for ceremony.',
      'Music rising from the square where silence was once required.',
      'He might not recognise the city.',
      'But he would recognise the stone.',
      'The palace is not only a monument to Diocletian.',
      'It is the living heart of Split.',
    ],
    relatedPlace: 'Diocletian’s Palace',
    relatedPoiKey: 'diocletian_palace',
    ctaAsk: 'Ask about the Palace today',
  },
];
