// whispers-data.js — Whispers of the Palace: 9 chapters
// Static content module. Images live in pwa/story/. Replace gradient fallbacks
// with real image paths once assets are ready. videoUrl is empty until production.

/* eslint-disable quotes */
const WHISPERS_CHAPTERS = [
  {
    id: 'ch01',
    number: '01',
    title: 'The Emperor and His Palace',
    subtitle: 'A Roman emperor, a palace by the sea, and the beginning of Split’s story.',
    shortText: 'Before Split became a city, it was the final home of one of Rome’s most powerful rulers.',
    mainText: [
      'Diocletian was one of the most influential emperors of the Roman world. He ruled at a time when the empire was vast, unstable and difficult to control, and his decisions reshaped the way Rome was governed.',
      'But his most unusual act was not a battle or a reform. It was his decision to step away from power. Unlike many emperors before him, Diocletian voluntarily abdicated and withdrew to a palace he had built on the Dalmatian coast.',
      'That palace was not only a private residence. It was a statement of order, power and memory — a place where imperial ceremony, military security and personal retreat came together in stone.',
    ],
    didYouKnow: 'Diocletian is one of the rare Roman emperors who voluntarily gave up power.',
    image: 'story/diocletian-palace-cover.jpg',
    gradient: 'linear-gradient(160deg, #1a0e2e 0%, #3a1a0e 60%, #2c1f14 100%)',
    videoUrl: '',
    videoLabel: 'Cinematic intro video coming later',
    relatedPlace: null,
    relatedPoiKey: null,
    ctaAsk: 'Ask Dioclea about Diocletian',
  },
  {
    id: 'ch02',
    number: '02',
    title: 'The Man Before the Palace',
    subtitle: 'From the world of Salona to the height of Roman power.',
    shortText: 'Diocletian’s story begins near Salona, long before the Palace was built.',
    mainText: [
      'Diocletian was born in Dalmatia, most likely near Salona, the great Roman city that stood just outside today’s Split. His origins were not those of an old aristocratic dynasty. Like many powerful figures of the late Roman Empire, he rose through the military world.',
      'The army was one of the few paths through which ability, discipline and ambition could carry a man to the highest levels of power. Diocletian advanced through this system and eventually became emperor in 284 AD.',
      'His background matters because it shaped the Palace itself. This was not the fantasy villa of a detached ruler. It was the retirement home of a soldier-emperor — practical, fortified, ceremonial and deeply connected to the landscape of his youth.',
    ],
    didYouKnow: 'Salona was one of the most important Roman cities on the eastern Adriatic.',
    image: 'story/salona-roman-dalmatia.jpg',
    gradient: 'linear-gradient(160deg, #2a1200 0%, #4a2c10 60%, #1a0e00 100%)',
    videoUrl: '',
    videoLabel: 'Optional future video: Salona to Palace transition',
    relatedPlace: 'Salona',
    relatedPoiKey: null,
    ctaAsk: 'Ask Dioclea about Salona',
  },
  {
    id: 'ch03',
    number: '03',
    title: 'The Soldier Emperor',
    subtitle: 'The ruler who tried to reorganize the Roman world.',
    shortText: 'Diocletian did not simply rule the empire — he tried to rebuild its structure.',
    mainText: [
      'When Diocletian came to power, the Roman Empire had been shaken by decades of crisis, civil wars, military pressure and rapid changes of rulers. Stability had become rare, and the empire was too large for one man to manage easily.',
      'Diocletian responded with major reforms. He strengthened the army, reorganized administration and introduced the Tetrarchy — a system in which power was shared between four rulers. It was an attempt to make the empire more governable, more secure and less dependent on a single person.',
      'The Palace in Split reflects that mentality. Its walls, gates and ordered layout reveal the mind of a ruler who valued structure, control and protection.',
    ],
    didYouKnow: 'The Tetrarchy divided imperial responsibility among four rulers, an ambitious attempt to stabilize the empire.',
    image: 'story/roman-tetrarchy.jpg',
    gradient: 'linear-gradient(160deg, #0e1a2e 0%, #1e3050 60%, #0e0e1a 100%)',
    videoUrl: '',
    videoLabel: 'Optional future video: animated empire map',
    relatedPlace: null,
    relatedPoiKey: null,
    ctaAsk: 'Ask Dioclea about the Tetrarchy',
  },
  {
    id: 'ch04',
    number: '04',
    title: 'Why Here? Salona, Sea and Water',
    subtitle: 'The coast, the Roman city and the water that made the Palace possible.',
    shortText: 'The Palace was not placed here by accident.',
    mainText: [
      'Diocletian’s Palace was built in a carefully chosen location. It stood close to Salona, the capital of the Roman province of Dalmatia, but also directly by the sea. This gave the Palace both connection and distance — near the urban and political world, yet set apart as an imperial residence.',
      'Water was essential. The nearby Jadro River supplied the Palace through an aqueduct, an impressive piece of Roman engineering that brought fresh water across the landscape. Without that system, such a residence could not function on this scale.',
      'The site combined everything Diocletian needed: access to Salona, protection, sea routes, fresh water and a landscape tied to his origins. The result was not just a palace, but a carefully engineered world.',
    ],
    didYouKnow: 'Parts of the ancient aqueduct system were later restored and continued to shape Split’s water supply.',
    image: 'story/jadro-aqueduct.jpg',
    gradient: 'linear-gradient(160deg, #0a2030 0%, #1a4050 60%, #0a1824 100%)',
    videoUrl: '',
    videoLabel: 'Optional future video: water flowing from Jadro to Palace',
    relatedPlace: 'Aqueduct / Jadro',
    relatedPoiKey: null,
    ctaAsk: 'Ask Dioclea about the aqueduct',
  },
  {
    id: 'ch05',
    number: '05',
    title: 'A Palace, a Fortress, a Home',
    subtitle: 'A residence built with the logic of a military mind.',
    shortText: 'Diocletian’s Palace was both luxurious and defensive.',
    mainText: [
      'Diocletian’s Palace is often called a palace, but it is not a palace in the usual sense. Its walls, towers and gates give it the character of a fortified structure, while its inner spaces reveal the ceremonial and residential life of an emperor.',
      'This combination makes it unique. The southern part, closer to the sea, was connected to the imperial apartments and private life. The northern part had a more functional and military character. The entire complex was organized with Roman precision.',
      'The Palace was not only built for comfort. It was built for status, security and order — a stone expression of the man who created it.',
    ],
    didYouKnow: 'The Palace combines features of a Roman villa, military camp and imperial ceremonial complex.',
    image: 'story/palace-fortress-home.jpg',
    gradient: 'linear-gradient(160deg, #1e1200 0%, #3a2a10 60%, #2c1f14 100%)',
    videoUrl: '',
    videoLabel: 'Optional future video: aerial reconstruction of the Palace',
    relatedPlace: 'Diocletian’s Palace',
    relatedPoiKey: null,
    ctaAsk: 'Ask Dioclea about the Palace layout',
  },
  {
    id: 'ch06',
    number: '06',
    title: 'The Heart of the Palace',
    subtitle: 'Peristyle, Vestibule and the ceremonial world of the emperor.',
    shortText: 'At the centre of the Palace, architecture became theatre.',
    mainText: [
      'The Peristyle was the ceremonial heart of Diocletian’s Palace. Surrounded by columns and framed by sacred and imperial spaces, it was the place where architecture communicated power.',
      'From here, one could approach the imperial apartments through the Vestibule, a striking circular space that still carries a powerful sense of transition. Today, the same stones are filled with visitors, music and everyday life, but the ceremonial rhythm of the place can still be felt.',
      'This is one of the most remarkable qualities of the Palace: spaces designed for imperial display have become part of the living city.',
    ],
    didYouKnow: 'The Vestibule is famous today for its acoustics, often used by singers and performers.',
    image: 'story/peristyle-vestibule.jpg',
    gradient: 'linear-gradient(160deg, #1a0e20 0%, #3a1a30 60%, #2c1414 100%)',
    videoUrl: '',
    videoLabel: 'Future video: today’s Peristyle transitioning into the Roman past',
    relatedPlace: 'Peristyle / Vestibule',
    relatedPoiKey: null,
    ctaAsk: 'Ask Dioclea about the Peristyle',
  },
  {
    id: 'ch07',
    number: '07',
    title: 'From Mausoleum to Cathedral',
    subtitle: 'The emperor’s tomb that became the Cathedral of Saint Domnius.',
    shortText: 'One of the Palace’s greatest historical reversals stands at its centre.',
    mainText: [
      'Diocletian built a mausoleum for himself within the Palace complex. It was intended as the final resting place of an emperor, surrounded by the symbols and architecture of Roman power.',
      'Over time, history transformed the meaning of this space. The mausoleum became the Cathedral of Saint Domnius, one of the most recognizable landmarks of Split. The transformation is deeply symbolic: an imperial tomb became a Christian cathedral dedicated to a local martyr.',
      'This change tells the larger story of the Palace itself. It did not remain frozen in Roman time. It was reused, reinterpreted and absorbed into the life of a new city.',
    ],
    didYouKnow: 'The Cathedral of Saint Domnius is considered one of the oldest cathedral buildings still in use in its original structure.',
    image: 'story/mausoleum-cathedral.jpg',
    gradient: 'linear-gradient(160deg, #1a1000 0%, #3a2800 60%, #1e1800 100%)',
    videoUrl: '',
    videoLabel: 'Future video: mausoleum to cathedral visual transition',
    relatedPlace: 'Cathedral of Saint Domnius',
    relatedPoiKey: null,
    ctaAsk: 'Ask Dioclea about the Cathedral',
  },
  {
    id: 'ch08',
    number: '08',
    title: 'Salona, the Lost Roman Capital',
    subtitle: 'The great city before Split.',
    shortText: 'Before Split rose inside the Palace walls, Salona was the centre of Roman Dalmatia.',
    mainText: [
      'Salona was once the capital of the Roman province of Dalmatia and one of the most important cities on this part of the Adriatic. It had city walls, baths, temples, an amphitheatre, basilicas and a large urban population.',
      'Its remains still lie near today’s Solin, only a short distance from Split. Walking through Salona means stepping into the world that shaped Diocletian long before his Palace became the heart of a city.',
      'As Salona declined in the early medieval period, life gradually shifted toward the protected walls of the Palace. In that movement, the Palace began its second life — not as an imperial residence, but as the foundation of Split.',
    ],
    didYouKnow: 'The ruins of Salona include an amphitheatre and early Christian remains.',
    image: 'story/salona-lost-capital.jpg',
    gradient: 'linear-gradient(160deg, #2a1400 0%, #4a2800 60%, #1e1000 100%)',
    videoUrl: '',
    videoLabel: 'Future video: Salona ruins and Roman city reconstruction',
    relatedPlace: 'Salona',
    relatedPoiKey: null,
    ctaAsk: 'Ask Dioclea about Salona ruins',
  },
  {
    id: 'ch09',
    number: '09',
    title: 'The Palace That Became Split',
    subtitle: 'How imperial stone became a living city.',
    shortText: 'The Palace survived because people moved into it, changed it and made it their own.',
    mainText: [
      'Many ancient monuments survive as ruins. Diocletian’s Palace survived differently. It became a city.',
      'Over the centuries, people built homes, shops, churches and streets within the Roman walls. Imperial halls became everyday passages. Ancient columns stood beside medieval houses. The Palace did not disappear; it adapted.',
      'This is why Split feels unlike almost anywhere else. The past is not separated behind a museum entrance. It is under your feet, above your head and around the corner. The Palace is not only a monument to Diocletian — it is the living heart of Split.',
    ],
    didYouKnow: 'Today, people still live and work inside the walls of Diocletian’s Palace.',
    image: 'story/palace-became-split.jpg',
    gradient: 'linear-gradient(160deg, #0a1a1a 0%, #1a3030 60%, #102020 100%)',
    videoUrl: '',
    videoLabel: 'Future video: Roman walls blending into modern Split life',
    relatedPlace: 'Diocletian’s Palace route',
    relatedPoiKey: null,
    ctaAsk: 'Ask Dioclea about the Palace today',
  },
];
